apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    app: run
spec:
  containers:
    - name: app
      image: gcr.io/gbot-418317/demo:v1.0.0
      ports:
        - containerPort: 8000
          name: http